package com.BrainBlitz.dto.response;

import com.BrainBlitz.enums.ExamType;
import com.BrainBlitz.enums.MockStatus;
import java.time.LocalDateTime;
import java.util.List;

public class MockResultResponse {

    // ─────────────────────────────────────────────
    // SESSION INFO
    // ─────────────────────────────────────────────

    private Long sessionId;
    private ExamType examType;
    private MockStatus status;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private Integer durationSeconds;

    // ─────────────────────────────────────────────
    // SCORE SUMMARY
    // ─────────────────────────────────────────────

    private int totalQuestions;
    private int attempted;
    private int correct;
    private int wrong;
    private int skipped;
    private double totalScore;
    private double maxPossibleScore;
    private double accuracyPercentage;

    // ─────────────────────────────────────────────
    // TOPIC WISE BREAKDOWN
    // ─────────────────────────────────────────────

    // One entry per subject + topic combination
    private List<TopicResultResponse> topicBreakdown;

    // ─────────────────────────────────────────────
    // ANSWER DETAILS
    // ─────────────────────────────────────────────

    // Full list of all answers with result
    // Used for detailed review page
    private List<MockAnswerResponse> answers;

    // ─────────────────────────────────────────────
    // AI STUDY PLAN
    // ─────────────────────────────────────────────

    // Generated by Claude API after submission
    // null until AI processes it
    private String aiStudyPlan;

    // ─────────────────────────────────────────────
    // USER LEVEL INFO
    // ─────────────────────────────────────────────

    // Level before this mock
    private int levelBefore;

    // Level after this mock
    private int levelAfter;

    // Whether level changed
    private boolean levelChanged;

    // ─────────────────────────────────────────────
    // GETTERS AND SETTERS
    // ─────────────────────────────────────────────

    public Long getSessionId() { return sessionId; }
    public void setSessionId(Long sessionId) { this.sessionId = sessionId; }

    public ExamType getExamType() { return examType; }
    public void setExamType(ExamType examType) { this.examType = examType; }

    public MockStatus getStatus() { return status; }
    public void setStatus(MockStatus status) { this.status = status; }

    public LocalDateTime getStartTime() { return startTime; }
    public void setStartTime(LocalDateTime startTime) { 
        this.startTime = startTime; 
    }

    public LocalDateTime getEndTime() { return endTime; }
    public void setEndTime(LocalDateTime endTime) { 
        this.endTime = endTime; 
    }

    public Integer getDurationSeconds() { return durationSeconds; }
    public void setDurationSeconds(Integer durationSeconds) { 
        this.durationSeconds = durationSeconds; 
    }

    public int getTotalQuestions() { return totalQuestions; }
    public void setTotalQuestions(int totalQuestions) { 
        this.totalQuestions = totalQuestions; 
    }

    public int getAttempted() { return attempted; }
    public void setAttempted(int attempted) { this.attempted = attempted; }

    public int getCorrect() { return correct; }
    public void setCorrect(int correct) { this.correct = correct; }

    public int getWrong() { return wrong; }
    public void setWrong(int wrong) { this.wrong = wrong; }

    public int getSkipped() { return skipped; }
    public void setSkipped(int skipped) { this.skipped = skipped; }

    public double getTotalScore() { return totalScore; }
    public void setTotalScore(double totalScore) { 
        this.totalScore = totalScore; 
    }

    public double getMaxPossibleScore() { return maxPossibleScore; }
    public void setMaxPossibleScore(double maxPossibleScore) { 
        this.maxPossibleScore = maxPossibleScore; 
    }

    public double getAccuracyPercentage() { return accuracyPercentage; }
    public void setAccuracyPercentage(double accuracyPercentage) { 
        this.accuracyPercentage = accuracyPercentage; 
    }

    public List<TopicResultResponse> getTopicBreakdown() { 
        return topicBreakdown; 
    }
    public void setTopicBreakdown(List<TopicResultResponse> topicBreakdown) { 
        this.topicBreakdown = topicBreakdown; 
    }

    public List<MockAnswerResponse> getAnswers() { return answers; }
    public void setAnswers(List<MockAnswerResponse> answers) { 
        this.answers = answers; 
    }

    public String getAiStudyPlan() { return aiStudyPlan; }
    public void setAiStudyPlan(String aiStudyPlan) { 
        this.aiStudyPlan = aiStudyPlan; 
    }

    public int getLevelBefore() { return levelBefore; }
    public void setLevelBefore(int levelBefore) { 
        this.levelBefore = levelBefore; 
    }

    public int getLevelAfter() { return levelAfter; }
    public void setLevelAfter(int levelAfter) { 
        this.levelAfter = levelAfter; 
    }

    public boolean isLevelChanged() { return levelChanged; }
    public void setLevelChanged(boolean levelChanged) { 
        this.levelChanged = levelChanged; 
    }
}