package com.BrainBlitz.entity;

import java.time.LocalDateTime;
import java.util.List;

import com.BrainBlitz.enums.ExamType;
import com.BrainBlitz.enums.MockSource;
import com.BrainBlitz.enums.MockStatus;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

@Entity
@Table(name = "mock_sessions")
public class MockSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Which user took this mock
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Which exam this mock was for
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ExamType examType;

    // DB or AI generated questions
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MockSource mockSource;   // DB, AI

    // User level at the time of this mock
    // Important — level changes over time
    // We need to know what level user was WHEN they took this mock
    @Column(nullable = false)
    private int userLevelAtTime;

    // Timing
    @Column(nullable = false)
    private LocalDateTime startTime;

    @Column
    private LocalDateTime endTime;

    // Duration in seconds
    // Calculated when mock is submitted
    @Column
    private Integer durationSeconds;

    // Question counts
    @Column(nullable = false)
    private int totalQuestions;

    @Column(nullable = false)
    private int attempted;

    @Column(nullable = false)
    private int correct;

    @Column(nullable = false)
    private int wrong;

    @Column(nullable = false)
    private int skipped;

    // Score
    @Column(nullable = false)
    private double totalScore;

    @Column(nullable = false)
    private double maxPossibleScore;

    @Column(nullable = false)
    private double accuracyPercentage;

    // Mock status
    // IN_PROGRESS → user is currently taking mock
    // COMPLETED   → user submitted mock
    // ABANDONED   → user closed without submitting
    // TIMED_OUT   → timer ran out
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MockStatus status;

    // AI generated study plan after mock
    // Generated by Claude API after submission
    // Stored here so user can view anytime
    @Column(columnDefinition = "TEXT")
    private String aiStudyPlan;

    // Flag — has performance been processed
    // false = not yet updated weak areas and level
    // true  = weak areas and level already updated
    @Column(nullable = false)
    private boolean isPerformanceProcessed = false;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column
    private LocalDateTime updatedAt;

    // Child relationship
    // All answers for this session
    @OneToMany(mappedBy = "mockSession",
               cascade = CascadeType.ALL,
               orphanRemoval = true)
    private List<MockAnswer> answers;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.attempted = 0;
        this.correct = 0;
        this.wrong = 0;
        this.skipped = 0;
        this.totalScore = 0;
        this.isPerformanceProcessed = false;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

	public MockSession(Long id, User user, ExamType examType, MockSource mockSource, int userLevelAtTime,
			LocalDateTime startTime, LocalDateTime endTime, Integer durationSeconds, int totalQuestions, int attempted,
			int correct, int wrong, int skipped, double totalScore, double maxPossibleScore, double accuracyPercentage,
			MockStatus status, String aiStudyPlan, boolean isPerformanceProcessed, LocalDateTime createdAt,
			LocalDateTime updatedAt, List<MockAnswer> answers) {
		super();
		this.id = id;
		this.user = user;
		this.examType = examType;
		this.mockSource = mockSource;
		this.userLevelAtTime = userLevelAtTime;
		this.startTime = startTime;
		this.endTime = endTime;
		this.durationSeconds = durationSeconds;
		this.totalQuestions = totalQuestions;
		this.attempted = attempted;
		this.correct = correct;
		this.wrong = wrong;
		this.skipped = skipped;
		this.totalScore = totalScore;
		this.maxPossibleScore = maxPossibleScore;
		this.accuracyPercentage = accuracyPercentage;
		this.status = status;
		this.aiStudyPlan = aiStudyPlan;
		this.isPerformanceProcessed = isPerformanceProcessed;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.answers = answers;
	}

	public MockSession() {
		super();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public ExamType getExamType() {
		return examType;
	}

	public void setExamType(ExamType examType) {
		this.examType = examType;
	}

	public MockSource getMockSource() {
		return mockSource;
	}

	public void setMockSource(MockSource mockSource) {
		this.mockSource = mockSource;
	}

	public int getUserLevelAtTime() {
		return userLevelAtTime;
	}

	public void setUserLevelAtTime(int userLevelAtTime) {
		this.userLevelAtTime = userLevelAtTime;
	}

	public LocalDateTime getStartTime() {
		return startTime;
	}

	public void setStartTime(LocalDateTime startTime) {
		this.startTime = startTime;
	}

	public LocalDateTime getEndTime() {
		return endTime;
	}

	public void setEndTime(LocalDateTime endTime) {
		this.endTime = endTime;
	}

	public Integer getDurationSeconds() {
		return durationSeconds;
	}

	public void setDurationSeconds(Integer durationSeconds) {
		this.durationSeconds = durationSeconds;
	}

	public int getTotalQuestions() {
		return totalQuestions;
	}

	public void setTotalQuestions(int totalQuestions) {
		this.totalQuestions = totalQuestions;
	}

	public int getAttempted() {
		return attempted;
	}

	public void setAttempted(int attempted) {
		this.attempted = attempted;
	}

	public int getCorrect() {
		return correct;
	}

	public void setCorrect(int correct) {
		this.correct = correct;
	}

	public int getWrong() {
		return wrong;
	}

	public void setWrong(int wrong) {
		this.wrong = wrong;
	}

	public int getSkipped() {
		return skipped;
	}

	public void setSkipped(int skipped) {
		this.skipped = skipped;
	}

	public double getTotalScore() {
		return totalScore;
	}

	public void setTotalScore(double totalScore) {
		this.totalScore = totalScore;
	}

	public double getMaxPossibleScore() {
		return maxPossibleScore;
	}

	public void setMaxPossibleScore(double maxPossibleScore) {
		this.maxPossibleScore = maxPossibleScore;
	}

	public double getAccuracyPercentage() {
		return accuracyPercentage;
	}

	public void setAccuracyPercentage(double accuracyPercentage) {
		this.accuracyPercentage = accuracyPercentage;
	}

	public MockStatus getStatus() {
		return status;
	}

	public void setStatus(MockStatus status) {
		this.status = status;
	}

	public String getAiStudyPlan() {
		return aiStudyPlan;
	}

	public void setAiStudyPlan(String aiStudyPlan) {
		this.aiStudyPlan = aiStudyPlan;
	}

	public boolean isPerformanceProcessed() {
		return isPerformanceProcessed;
	}

	public void setPerformanceProcessed(boolean isPerformanceProcessed) {
		this.isPerformanceProcessed = isPerformanceProcessed;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	public List<MockAnswer> getAnswers() {
		return answers;
	}

	public void setAnswers(List<MockAnswer> answers) {
		this.answers = answers;
	}
    
    
}
